In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
penguins = sns.load_dataset("penguins")
penguins.to_csv('../data/raw/penguins.csv', index=False)

In [3]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [4]:
dicionario = pd.DataFrame([
    {
        "variavel":"species",
        "descricao": "Nome da Espécie",
        "tipo":"qualitativa",
        "subtipo":"nominal"
    },{
        "variavel":"island",
        "descricao": "Ilha que foi feita a medição",
        "tipo":"qualitativa",
        "subtipo":"nominal"
    },{
        "variavel":"bill_length_mm",
        "descricao": "Comprimento do bico em mm",
        "tipo":"quantitativa",
        "subtipo":"continua"
    },{
        "variavel":"bill_depth_mm",
        "descricao": "Profunidade (altura) do bico em mm",
        "tipo":"quantitativa",
        "subtipo":"continua"
    },{
        "variavel":"flipper_length_mm",
        "descricao": "Comprimento da nadadeira em mm",
        "tipo":"quantitativa",
        "subtipo":"continua"
    },{
        "variavel":"body_mass_g",
        "descricao": "Massa do corpo em gramas",
        "tipo":"quantitativa",
        "subtipo":"continua"
    },{
        "variavel":"sex",
        "descricao": "Sexo dos penguins",
        "tipo":"qualitativa",
        "subtipo":"nominal"
    }
])

In [5]:
dicionario

,variavel,descricao,tipo,subtipo
0,species,Nome da Espécie,qualitativa,nominal
1,island,Ilha que foi feita a medição,qualitativa,nominal
2,bill_length_mm,Comprimento do bico em mm,quantitativa,continua
3,bill_depth_mm,Profunidade (altura) do bico em mm,quantitativa,continua
4,flipper_length_mm,Comprimento da nadadeira em mm,quantitativa,continua
5,body_mass_g,Massa do corpo em gramas,quantitativa,continua
6,sex,Sexo dos penguins,qualitativa,nominal

In [6]:
dicionario.to_csv('../data/external/dictionary.csv', index=False)